Update minimal-install

diff --git a/minimal-install b/minimal-install
--- a/minimal-install
+++ b/minimal-install
@@ -1,19 +1,19 @@
 #!/bin/sh
 
-quit()
+error()
 {
 	echo "Installation failed, try again."
 	exit
 }
 
 ### basic install
-sudo pacman -S --needed --noconfirm $(awk '/#M/{print $1}' resources/pkg-list) || quit
+sudo pacman -S --needed --noconfirm $(awk '/#M/{print $1}' resources/pkg-list) || error
 
 ### install aur helper
-which yay && echo "AUR helper already installed, skipping." || ./install-aur-helper || quit
+which yay && echo "AUR helper already installed, skipping." || ./install-aur-helper || error
 
 ### suckless
-which st dwm dmenu dwmblocks && echo "Window manager already installed, skipping." || ./install-window-manager || quit
+which st dwm dmenu dwmblocks && echo "Window manager already installed, skipping." || ./install-window-manager || error
 
 ### user configuration
 ./user-config
